version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@react-native-community/masked-view"
    versions:
    - 0.1.10
  - dependency-name: date-fns
    versions:
    - 2.16.1
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.0
    - 2.20.1
    - 2.20.2
  - dependency-name: styled-components
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: react-native-screens
    versions:
    - 2.17.1
    - 2.18.0
    - 2.18.1
    - 3.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.8
  - dependency-name: "@react-navigation/bottom-tabs"
    versions:
    - 5.11.7
    - 5.11.8
  - dependency-name: react-redux
    versions:
    - 7.2.2
